language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: steven.jmiller@gmail.com
  api_key:
    secure: KNEBEE7H/spulFtDgcRcz6roeE4c8fXXLFD6evADMeTb3qtxsDI9rkz9KIyaf9qjtVdpNmgT8rGtMR0psnmfKTUPhf3PNpwzUZ8aJKNwf9rjs1Xro1AHaIFRkUE0F4ox2i7/cMNCAiygJWXT/yKN1bJPE/3lT3hJLC+HPSxlrpM=
  on:
    tags: true
    repo: yargalot/Email-Builder
